package com.example.paypaycodechallange.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

@JsonClass(generateAdapter = true)
data class Quotes(
    @Json(name = "USDAED")
    val uSDAED: Double,
    @Json(name = "USDAFN")
    val uSDAFN: Double,
    @Json(name = "USDALL")
    val uSDALL: Double,
    @Json(name = "USDAMD")
    val uSDAMD: Double,
    @Json(name = "USDANG")
    val uSDANG: Double,
    @Json(name = "USDAOA")
    val uSDAOA: Double,
    @Json(name = "USDARS")
    val uSDARS: Double,
    @Json(name = "USDAUD")
    val uSDAUD: Double,
    @Json(name = "USDAWG")
    val uSDAWG: Double,
    @Json(name = "USDAZN")
    val uSDAZN: Double,
    @Json(name = "USDBAM")
    val uSDBAM: Double,
    @Json(name = "USDBBD")
    val uSDBBD: Double,
    @Json(name = "USDBDT")
    val uSDBDT: Double,
    @Json(name = "USDBGN")
    val uSDBGN: Double,
    @Json(name = "USDBHD")
    val uSDBHD: Double,
    @Json(name = "USDBIF")
    val uSDBIF: Double,
    @Json(name = "USDBMD")
    val uSDBMD: Int,
    @Json(name = "USDBND")
    val uSDBND: Double,
    @Json(name = "USDBOB")
    val uSDBOB: Double,
    @Json(name = "USDBRL")
    val uSDBRL: Double,
    @Json(name = "USDBSD")
    val uSDBSD: Double,
    @Json(name = "USDBTC")
    val uSDBTC: Double,
    @Json(name = "USDBTN")
    val uSDBTN: Double,
    @Json(name = "USDBWP")
    val uSDBWP: Double,
    @Json(name = "USDBYN")
    val uSDBYN: Double,
    @Json(name = "USDBYR")
    val uSDBYR: Int,
    @Json(name = "USDBZD")
    val uSDBZD: Double,
    @Json(name = "USDCAD")
    val uSDCAD: Double,
    @Json(name = "USDCDF")
    val uSDCDF: Double,
    @Json(name = "USDCHF")
    val uSDCHF: Double,
    @Json(name = "USDCLF")
    val uSDCLF: Double,
    @Json(name = "USDCLP")
    val uSDCLP: Double,
    @Json(name = "USDCNY")
    val uSDCNY: Double,
    @Json(name = "USDCOP")
    val uSDCOP: Double,
    @Json(name = "USDCRC")
    val uSDCRC: Double,
    @Json(name = "USDCUC")
    val uSDCUC: Int,
    @Json(name = "USDCUP")
    val uSDCUP: Double,
    @Json(name = "USDCVE")
    val uSDCVE: Double,
    @Json(name = "USDCZK")
    val uSDCZK: Double,
    @Json(name = "USDDJF")
    val uSDDJF: Double,
    @Json(name = "USDDKK")
    val uSDDKK: Double,
    @Json(name = "USDDOP")
    val uSDDOP: Double,
    @Json(name = "USDDZD")
    val uSDDZD: Double,
    @Json(name = "USDEGP")
    val uSDEGP: Double,
    @Json(name = "USDERN")
    val uSDERN: Double,
    @Json(name = "USDETB")
    val uSDETB: Double,
    @Json(name = "USDEUR")
    val uSDEUR: Double,
    @Json(name = "USDFJD")
    val uSDFJD: Double,
    @Json(name = "USDFKP")
    val uSDFKP: Double,
    @Json(name = "USDGBP")
    val uSDGBP: Double,
    @Json(name = "USDGEL")
    val uSDGEL: Double,
    @Json(name = "USDGGP")
    val uSDGGP: Double,
    @Json(name = "USDGHS")
    val uSDGHS: Double,
    @Json(name = "USDGIP")
    val uSDGIP: Double,
    @Json(name = "USDGMD")
    val uSDGMD: Double,
    @Json(name = "USDGNF")
    val uSDGNF: Double,
    @Json(name = "USDGTQ")
    val uSDGTQ: Double,
    @Json(name = "USDGYD")
    val uSDGYD: Double,
    @Json(name = "USDHKD")
    val uSDHKD: Double,
    @Json(name = "USDHNL")
    val uSDHNL: Double,
    @Json(name = "USDHRK")
    val uSDHRK: Double,
    @Json(name = "USDHTG")
    val uSDHTG: Double,
    @Json(name = "USDHUF")
    val uSDHUF: Double,
    @Json(name = "USDIDR")
    val uSDIDR: Double,
    @Json(name = "USDILS")
    val uSDILS: Double,
    @Json(name = "USDIMP")
    val uSDIMP: Double,
    @Json(name = "USDINR")
    val uSDINR: Double,
    @Json(name = "USDIQD")
    val uSDIQD: Double,
    @Json(name = "USDIRR")
    val uSDIRR: Double,
    @Json(name = "USDISK")
    val uSDISK: Double,
    @Json(name = "USDJEP")
    val uSDJEP: Double,
    @Json(name = "USDJMD")
    val uSDJMD: Double,
    @Json(name = "USDJOD")
    val uSDJOD: Double,
    @Json(name = "USDJPY")
    val uSDJPY: Double,
    @Json(name = "USDKES")
    val uSDKES: Double,
    @Json(name = "USDKGS")
    val uSDKGS: Double,
    @Json(name = "USDKHR")
    val uSDKHR: Double,
    @Json(name = "USDKMF")
    val uSDKMF: Double,
    @Json(name = "USDKPW")
    val uSDKPW: Double,
    @Json(name = "USDKRW")
    val uSDKRW: Double,
    @Json(name = "USDKWD")
    val uSDKWD: Double,
    @Json(name = "USDKYD")
    val uSDKYD: Double,
    @Json(name = "USDKZT")
    val uSDKZT: Double,
    @Json(name = "USDLAK")
    val uSDLAK: Double,
    @Json(name = "USDLBP")
    val uSDLBP: Double,
    @Json(name = "USDLKR")
    val uSDLKR: Double,
    @Json(name = "USDLRD")
    val uSDLRD: Double,
    @Json(name = "USDLSL")
    val uSDLSL: Double,
    @Json(name = "USDLTL")
    val uSDLTL: Double,
    @Json(name = "USDLVL")
    val uSDLVL: Double,
    @Json(name = "USDLYD")
    val uSDLYD: Double,
    @Json(name = "USDMAD")
    val uSDMAD: Double,
    @Json(name = "USDMDL")
    val uSDMDL: Double,
    @Json(name = "USDMGA")
    val uSDMGA: Double,
    @Json(name = "USDMKD")
    val uSDMKD: Double,
    @Json(name = "USDMMK")
    val uSDMMK: Double,
    @Json(name = "USDMNT")
    val uSDMNT: Double,
    @Json(name = "USDMOP")
    val uSDMOP: Double,
    @Json(name = "USDMRO")
    val uSDMRO: Double,
    @Json(name = "USDMUR")
    val uSDMUR: Double,
    @Json(name = "USDMVR")
    val uSDMVR: Double,
    @Json(name = "USDMWK")
    val uSDMWK: Double,
    @Json(name = "USDMXN")
    val uSDMXN: Double,
    @Json(name = "USDMYR")
    val uSDMYR: Double,
    @Json(name = "USDMZN")
    val uSDMZN: Double,
    @Json(name = "USDNAD")
    val uSDNAD: Double,
    @Json(name = "USDNGN")
    val uSDNGN: Double,
    @Json(name = "USDNIO")
    val uSDNIO: Double,
    @Json(name = "USDNOK")
    val uSDNOK: Double,
    @Json(name = "USDNPR")
    val uSDNPR: Double,
    @Json(name = "USDNZD")
    val uSDNZD: Double,
    @Json(name = "USDOMR")
    val uSDOMR: Double,
    @Json(name = "USDPAB")
    val uSDPAB: Double,
    @Json(name = "USDPEN")
    val uSDPEN: Double,
    @Json(name = "USDPGK")
    val uSDPGK: Double,
    @Json(name = "USDPHP")
    val uSDPHP: Double,
    @Json(name = "USDPKR")
    val uSDPKR: Double,
    @Json(name = "USDPLN")
    val uSDPLN: Double,
    @Json(name = "USDPYG")
    val uSDPYG: Double,
    @Json(name = "USDQAR")
    val uSDQAR: Double,
    @Json(name = "USDRON")
    val uSDRON: Double,
    @Json(name = "USDRSD")
    val uSDRSD: Double,
    @Json(name = "USDRUB")
    val uSDRUB: Double,
    @Json(name = "USDRWF")
    val uSDRWF: Double,
    @Json(name = "USDSAR")
    val uSDSAR: Double,
    @Json(name = "USDSBD")
    val uSDSBD: Double,
    @Json(name = "USDSCR")
    val uSDSCR: Double,
    @Json(name = "USDSDG")
    val uSDSDG: Double,
    @Json(name = "USDSEK")
    val uSDSEK: Double,
    @Json(name = "USDSGD")
    val uSDSGD: Double,
    @Json(name = "USDSHP")
    val uSDSHP: Double,
    @Json(name = "USDSLL")
    val uSDSLL: Double,
    @Json(name = "USDSOS")
    val uSDSOS: Double,
    @Json(name = "USDSRD")
    val uSDSRD: Double,
    @Json(name = "USDSTD")
    val uSDSTD: Double,
    @Json(name = "USDSVC")
    val uSDSVC: Double,
    @Json(name = "USDSYP")
    val uSDSYP: Double,
    @Json(name = "USDSZL")
    val uSDSZL: Double,
    @Json(name = "USDTHB")
    val uSDTHB: Double,
    @Json(name = "USDTJS")
    val uSDTJS: Double,
    @Json(name = "USDTMT")
    val uSDTMT: Double,
    @Json(name = "USDTND")
    val uSDTND: Double,
    @Json(name = "USDTOP")
    val uSDTOP: Double,
    @Json(name = "USDTRY")
    val uSDTRY: Double,
    @Json(name = "USDTTD")
    val uSDTTD: Double,
    @Json(name = "USDTWD")
    val uSDTWD: Double,
    @Json(name = "USDTZS")
    val uSDTZS: Double,
    @Json(name = "USDUAH")
    val uSDUAH: Double,
    @Json(name = "USDUGX")
    val uSDUGX: Double,
    @Json(name = "USDUSD")
    val uSDUSD: Int,
    @Json(name = "USDUYU")
    val uSDUYU: Double,
    @Json(name = "USDUZS")
    val uSDUZS: Double,
    @Json(name = "USDVEF")
    val uSDVEF: Double,
    @Json(name = "USDVND")
    val uSDVND: Int,
    @Json(name = "USDVUV")
    val uSDVUV: Double,
    @Json(name = "USDWST")
    val uSDWST: Double,
    @Json(name = "USDXAF")
    val uSDXAF: Double,
    @Json(name = "USDXAG")
    val uSDXAG: Double,
    @Json(name = "USDXAU")
    val uSDXAU: Double,
    @Json(name = "USDXCD")
    val uSDXCD: Double,
    @Json(name = "USDXDR")
    val uSDXDR: Double,
    @Json(name = "USDXOF")
    val uSDXOF: Double,
    @Json(name = "USDXPF")
    val uSDXPF: Double,
    @Json(name = "USDYER")
    val uSDYER: Double,
    @Json(name = "USDZAR")
    val uSDZAR: Double,
    @Json(name = "USDZMK")
    val uSDZMK: Double,
    @Json(name = "USDZMW")
    val uSDZMW: Double,
    @Json(name = "USDZWL")
    val uSDZWL: Double
)